name: "CI"
# Disabling, because build is pretty slow
on:
  #pull_request:
  #push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAINLINE: refs/heads/master
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org
            binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
            binary-caches-parallel-connections = 40
            sandbox = true
      - name: "Full build (GHCJS) 🔧"
        run: |
          (cd style && nix-shell -p entr --run 'nix-shell -j4 -A shell --run "ls main.css | entr sh -c \"npm run compile\""')
          nix-build -j4 -A exe
