name: "CI"
on:
  #pull_request:
  #push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: iohk
    - run: cachix use iohk
    - run: nix-build -A g.components.all
