name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAINLINE: refs/heads/master
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - run: nix-build -j4
      - name: Publish Docker image
        if: ${{ github.ref == env.MAINLINE && runner.os == 'Linux' }}
        run: |
          docker load -i $(nix-build docker.nix --argstr tag latest)
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u srid --password-stdin
          docker push ghcr.io/srid/emanote:latest
