name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAINLINE: refs/heads/master
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - run: cd emanote-cli && nix-build -j4
